name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master  # or 'master' or your default branch

# env:
#   ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
#   ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
#   ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18  # or whatever version you use

      - name: Install dependencies
        run: npm ci

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
